### ISSUE TITLE
Puppet Forge Module Update

### ISSUE THREAD

**Issue by tenajsystems** [MiamiOH/puppet-duo_authproxy#14]
@edestecd and @kobybr Do you by any chance have a timeline on when the module on the forge will be updated?

**Comment by edestecd** [comment]
I tried to push to the forge yesterday but the pipeline failed.
As soon as this is merged: https://github.com/MiamiOH/puppet-duo_authproxy/pull/13

**Comment by kekogya** [comment]
> 
> 
> I tried to push to the forge yesterday but the pipeline failed.
> As soon as this is merged: #13

Thank you!

**Comment by tenajsystems** [comment]
> 
> 
> I tried to push to the forge yesterday but the pipeline failed.
> As soon as this is merged: #13

Thank you!

**Comment by edestecd** [comment]
1.0.0 is on the forge

**Comment by tenajsystems** [comment]
Thank you!
